BRONX = "Bronx"
BROOKLYN = "Brooklyn"
MANHATTAN = "Manhattan"
QUEENS = "Queens"
STATEN_ISLAND = "Staten Island"

NEIGHBORHOOD_BURROUGH_MAPPING = {
    "bedford park": BRONX,
    "belmont": BRONX,
    "fordham": BRONX,
    "fordham heights": BRONX,
    "fordham manor": BRONX,
    "jerome park": BRONX,
    "kingsbridge": BRONX,
    "kingsbridge heights": BRONX,
    "van cortlandt village": BRONX,
    "marble hill": BRONX,
    "norwood": BRONX,
    "riverdale": BRONX,
    "central riversale": BRONX,
    "fieldston": BRONX,
    "hudson hill": BRONX,
    "north riverdale": BRONX,
    "spuyten duyvil": BRONX,
    "university heights": BRONX,
    "woodlawn heights": BRONX,
    "bathgate": BRONX,
    "claremont": BRONX,
    "concourse": BRONX,
    "east tremont": BRONX,
    "highbridge": BRONX,
    "hunts point": BRONX,
    "longwood": BRONX,
    "foxhurst": BRONX,
    "woodstock": BRONX,
    "melrose": BRONX,
    "morris heights": BRONX,
    "morrisania": BRONX,
    "crotona park east": BRONX,
    "mott haven": BRONX,
    "port morris": BRONX,
    "the hub": BRONX,
    "tremont": BRONX,
    "fairmount": BRONX,
    "mount eden": BRONX,
    "mount hope": BRONX,
    "west farms": BRONX,
    "allerton": BRONX,
    "bronxwood": BRONX,
    "laconia": BRONX,
    "baychester": BRONX,
    "bronxdale": BRONX,
    "city island": BRONX,
    "co-op city": BRONX,
    "eastchester": BRONX,
    "edenwald": BRONX,
    "pelham gardens": BRONX,
    "pelham parkway": BRONX,
    "wakefield": BRONX,
    "washingtonville": BRONX,
    "williamsbridge": BRONX,
    "olinville": BRONX,
    "bronx river": BRONX,
    "bruckner": BRONX,
    "clason point": BRONX,
    "country club": BRONX,
    "harding park": BRONX,
    "morris park": BRONX,
    "indian village": BRONX,
    "parkchester": BRONX,
    "park versailles": BRONX,
    "pelham bay": BRONX,
    "soundview": BRONX,
    "schuylerville": BRONX,
    "throggs neck": BRONX,
    "unionport": BRONX,
    "castle hill": BRONX,
    "van nest": BRONX,
    "westchester heights": BRONX,
    "westchester square": BRONX,
    "crown heights": BROOKLYN,
    "weeksville": BROOKLYN,
    "flatbush": BROOKLYN,
    "beverley squares": BROOKLYN,
    "ditmas park": BROOKLYN,
    "east flatbush": BROOKLYN,
    "farragut": BROOKLYN,
    "remsen village": BROOKLYN,
    "fiske terrace": BROOKLYN,
    "pigtown": BROOKLYN,
    "wingate": BROOKLYN,
    "prospect park": BROOKLYN,
    "prospect lefferts gardens": BROOKLYN,
    "prospect park south": BROOKLYN,
    "windsor terrace": BROOKLYN,
    "kensington": BROOKLYN,
    "ocean parkway": BROOKLYN,
    "parkville": BROOKLYN,
    "brownsville": BROOKLYN,
    "canarsie": BROOKLYN,
    "east new york": BROOKLYN,
    "city line": BROOKLYN,
    "cypress hills": BROOKLYN,
    "new lots": BROOKLYN,
    "spring creek": BROOKLYN,
    "starrett city": BROOKLYN,
    "highland park": BROOKLYN,
    "bedford-stuyvesant": BROOKLYN,
    "bedford": BROOKLYN,
    "ocean hill": BROOKLYN,
    "stuyvesant heights": BROOKLYN,
    "bushwick": BROOKLYN,
    "wyckoff heights": BROOKLYN,
    "east williamsburg": BROOKLYN,
    "greenpoint": BROOKLYN,
    "little poland": BROOKLYN,
    "williamsburg": BROOKLYN,
    "brooklyn heights": BROOKLYN,
    "brooklyn navy yard": BROOKLYN,
    "admiral's row": BROOKLYN,
    "cadman plaza": BROOKLYN,
    "clinton hill": BROOKLYN,
    "downtown brooklyn": BROOKLYN,
    "bridge plaza": BROOKLYN,
    "rambo": BROOKLYN,
    "dumbo": BROOKLYN,
    "fulton ferry": BROOKLYN,
    "fort greene": BROOKLYN,
    "prospect heights": BROOKLYN,
    "pacific park": BROOKLYN,
    "vinegar hill": BROOKLYN,
    "south brookly": BROOKLYN,
    "boerum hill": BROOKLYN,
    "carroll gardens": BROOKLYN,
    "columbia street waterfront district": BROOKLYN,
    "cobble hill": BROOKLYN,
    "gowanus": BROOKLYN,
    "park slope": BROOKLYN,
    "south park slope": BROOKLYN,
    "greenwood heights": BROOKLYN,
    "red hook": BROOKLYN,
    "barren island": BROOKLYN,
    "bergen beach and georgetown": BROOKLYN,
    "coney island": BROOKLYN,
    "brighton beach": BROOKLYN,
    "manhattan beach": BROOKLYN,
    "sea gate": BROOKLYN,
    "sheepshead bay and madison": BROOKLYN,
    "homecrest": BROOKLYN,
    "midwood": BROOKLYN,
    "flatlands": BROOKLYN,
    "gerritsen beach": BROOKLYN,
    "gravesend": BROOKLYN,
    "white sands": BROOKLYN,
    "marine park": BROOKLYN,
    "mill basin": BROOKLYN,
    "plumb beach": BROOKLYN,
    "bay ridge": BROOKLYN,
    "fort hamilton": BROOKLYN,
    "bensonhurst": BROOKLYN,
    "bath beach": BROOKLYN,
    "new utrecht": BROOKLYN,
    "borough park": BROOKLYN,
    "mapleton": BROOKLYN,
    "dyker heights": BROOKLYN,
    "sunset park": BROOKLYN,
    "sunset industrial park": BROOKLYN,
    "upper manhattan": MANHATTAN,
    "inwood": MANHATTAN,
    "fort george": MANHATTAN,
    "washington heights": MANHATTAN,
    "hudson heights": MANHATTAN,
    "west harlem": MANHATTAN,
    "hamilton heights": MANHATTAN,
    "manhattanville": MANHATTAN,
    "morningside heights": MANHATTAN,
    "central harlem": MANHATTAN,
    "harlem": MANHATTAN,
    "st. nicholas historic district": MANHATTAN,
    "astor row": MANHATTAN,
    "sugar hill": MANHATTAN,
    "marcus gravey park": MANHATTAN,
    "le petit senegal": MANHATTAN,
    "east harlem": MANHATTAN,
    "upper east side": MANHATTAN,
    "lenox hill": MANHATTAN,
    "carnegie hill": MANHATTAN,
    "yorkville": MANHATTAN,
    "upper west side": MANHATTAN,
    "manhattan valley": MANHATTAN,
    "lincoln square": MANHATTAN,
    "midtown": MANHATTAN,
    "colombus circle": MANHATTAN,
    "sutton place": MANHATTAN,
    "rockefeller center": MANHATTAN,
    "diamond district": MANHATTAN,
    "theater district": MANHATTAN,
    "turtle bay": MANHATTAN,
    "midtown east": MANHATTAN,
    "tudor city": MANHATTAN,
    "little brazil": MANHATTAN,
    "times square": MANHATTAN,
    "hudson yards": MANHATTAN,
    "midtown west": MANHATTAN,
    "hell's kitchen": MANHATTAN,
    "garment district": MANHATTAN,
    "herald square": MANHATTAN,
    "koreatown": MANHATTAN,
    "murray hill": MANHATTAN,
    "tenderloin": MANHATTAN,
    "madison square": MANHATTAN,
    "flower district": MANHATTAN,
    "brookdale": MANHATTAN,
    "kips bay": MANHATTAN,
    "rose hill": MANHATTAN,
    "nomad": MANHATTAN,
    "peter cooper village": MANHATTAN,
    "chelsea": MANHATTAN,
    "flatiron district": MANHATTAN,
    "gramercy park": MANHATTAN,
    "stuyvesant square": MANHATTAN,
    "union square": MANHATTAN,
    "meatpacking district": MANHATTAN,
    "waterside plaza": MANHATTAN,
    "downtown manhattan": MANHATTAN,
    "little gramercy": MANHATTAN,
    "alphabet city and loisaida": MANHATTAN,
    "east village": MANHATTAN,
    "greenwich village": MANHATTAN,
    "noho": MANHATTAN,
    "bowery": MANHATTAN,
    "west village": MANHATTAN,
    "lower east side": MANHATTAN,
    "soho": MANHATTAN,
    "nolita": MANHATTAN,
    "little australia": MANHATTAN,
    "little italy": MANHATTAN,
    "chinatown": MANHATTAN,
    "financial district": MANHATTAN,
    "five points": MANHATTAN,
    "cooperative village": MANHATTAN,
    "two bridges": MANHATTAN,
    "tribeca": MANHATTAN,
    "civic center": MANHATTAN,
    "radio row": MANHATTAN,
    "south street seaport historical district": MANHATTAN,
    "battery park city": MANHATTAN,
    "little syria": MANHATTAN,
    "roosevelt island": MANHATTAN,
    "astoria": QUEENS,
    "astoria heights": QUEENS,
    "ditmars": QUEENS,
    "steinway": QUEENS,
    "little egypt": QUEENS,
    "jackson heights": QUEENS,
    "long island city": QUEENS,
    "blissville": QUEENS,
    "hunters point": QUEENS,
    "dutch kills": QUEENS,
    "queensbridge": QUEENS,
    "queensview": QUEENS,
    "queens west": QUEENS,
    "ravenswood": QUEENS,
    "sunnyside": QUEENS,
    "sunnyside gardens": QUEENS,
    "bayside": QUEENS,
    "bay terrace": QUEENS,
    "bayside hills": QUEENS,
    "fort totten": QUEENS,
    "oakland gardens": QUEENS,
    "bellerose": QUEENS,
    "college point": QUEENS,
    "douglaston-little neck": QUEENS,
    "douglaston": QUEENS,
    "douglas bay": QUEENS,
    "douglas manor": QUEENS,
    "douglaston hill": QUEENS,
    "douglaston park": QUEENS,
    "winchester estates": QUEENS,
    "little neck": QUEENS,
    "pines": QUEENS,
    "little neck hill": QUEENS,
    "westmoreland": QUEENS,
    "flushing": QUEENS,
    "auburndale": QUEENS,
    "broadway-flushing": QUEENS,
    "bowne park": QUEENS,
    "downtown flushing": QUEENS,
    "kew gardens hill": QUEENS,
    "linden hill": QUEENS,
    "willets point": QUEENS,
    "pomonok": QUEENS,
    "electchester": QUEENS,
    "queensboro hill": QUEENS,
    "floral park": QUEENS,
    "fresh meadows": QUEENS,
    "hillcrest": QUEENS,
    "utopia": QUEENS,
    "glen oaks": QUEENS,
    "north shore towers": QUEENS,
    "whitestone": QUEENS,
    "beechhurst": QUEENS,
    "clearview": QUEENS,
    "malba": QUEENS,
    "briarwood": QUEENS,
    "corona": QUEENS,
    "lefrak city": QUEENS,
    "north corona": QUEENS,
    "east elmhurst": QUEENS,
    "elmhurst": QUEENS,
    "forest hills": QUEENS,
    "forest hills gardens": QUEENS,
    "fresh pond": QUEENS,
    "glendale": QUEENS,
    "kew gardens": QUEENS,
    "maspeth": QUEENS,
    "middle village": QUEENS,
    "rego park": QUEENS,
    "ridgewood": QUEENS,
    "woodside": QUEENS,
    "bellaire": QUEENS,
    "brookville": QUEENS,
    "cambria heights": QUEENS,
    "hollis hills": QUEENS,
    "hollis": QUEENS,
    "holliswood": QUEENS,
    "jamaica": QUEENS,
    "jamaica estates": QUEENS,
    "jamaica hills": QUEENS,
    "laurelton": QUEENS,
    "meadowmere": QUEENS,
    "queensvillage": QUEENS,
    "rochdale village": QUEENS,
    "rosedale": QUEENS,
    "saint albans": QUEENS,
    "south jamaica": QUEENS,
    "springfield gardens": QUEENS,
    "warnerville": QUEENS,
    "the hole": QUEENS,
    "howard beach": QUEENS,
    "hamilton beach": QUEENS,
    "howard park": QUEENS,
    "lindenwood": QUEENS,
    "old howard beach": QUEENS,
    "ramblersville": QUEENS,
    "rockwood park": QUEENS,
    "ozone park": QUEENS,
    "south ozone park": QUEENS,
    "tudor village": QUEENS,
    "richmond hill": QUEENS,
    "woodhaven": QUEENS,
    "arverne": QUEENS,
    "bayswater": QUEENS,
    "belle harbor": QUEENS,
    "breezy point": QUEENS,
    "broad channel": QUEENS,
    "edgemere": QUEENS,
    "far rockaway": QUEENS,
    "hammels": QUEENS,
    "neponsit": QUEENS,
    "rockaway beach": QUEENS,
    "rockaway park": QUEENS,
    "roxbury": QUEENS,
    "seaside": QUEENS,
    "annadale": STATEN_ISLAND,
    "arden heights": STATEN_ISLAND,
    "arlington": STATEN_ISLAND,
    "arrochar": STATEN_ISLAND,
    "bloomfield": STATEN_ISLAND,
    "brighton heights": STATEN_ISLAND,
    "bulls head": STATEN_ISLAND,
    "castleton corners": STATEN_ISLAND,
    "charleston": STATEN_ISLAND,
    "clifton": STATEN_ISLAND,
    "concord": STATEN_ISLAND,
    "dongan hills": STATEN_ISLAND,
    "egbertville": STATEN_ISLAND,
    "elm park": STATEN_ISLAND,
    "eltingville": STATEN_ISLAND,
    "emerson hill": STATEN_ISLAND,
    "fort wadsworth": STATEN_ISLAND,
    "graniteville": STATEN_ISLAND,
    "grant city": STATEN_ISLAND,
    "grasmere": STATEN_ISLAND,
    "great kills": STATEN_ISLAND,
    "greenridge": STATEN_ISLAND,
    "grymes hill": STATEN_ISLAND,
    "hamilton park": STATEN_ISLAND,
    "heartland village": STATEN_ISLAND,
    "huguenot": STATEN_ISLAND,
    "lighthouse hill": STATEN_ISLAND,
    "livingston": STATEN_ISLAND,
    "manor heights": STATEN_ISLAND,
    "mariners harbor": STATEN_ISLAND,
    "meiers corners": STATEN_ISLAND,
    "midland beach": STATEN_ISLAND,
    "new brighton": STATEN_ISLAND,
    "new dorp": STATEN_ISLAND,
    "new springville": STATEN_ISLAND,
    "oakwood": STATEN_ISLAND,
    "old place": STATEN_ISLAND,
    "old town": STATEN_ISLAND,
    "pleasant plains": STATEN_ISLAND,
    "port ivory": STATEN_ISLAND,
    "port richmond": STATEN_ISLAND,
    "prince's bay": STATEN_ISLAND,
    "randall manor": STATEN_ISLAND,
    "richmond valley": STATEN_ISLAND,
    "richmondtown": STATEN_ISLAND,
    "rosebank": STATEN_ISLAND,
    "rossville": STATEN_ISLAND,
    "saint george": STATEN_ISLAND,
    "sandy ground": STATEN_ISLAND,
    "shore acres": STATEN_ISLAND,
    "silver lake": STATEN_ISLAND,
    "south beach": STATEN_ISLAND,
    "stapleton": STATEN_ISLAND,
    "stapleton heights": STATEN_ISLAND,
    "todt hill": STATEN_ISLAND,
    "tompkinsville": STATEN_ISLAND,
    "tottenville": STATEN_ISLAND,
    "travis": STATEN_ISLAND,
    "ward hill": STATEN_ISLAND,
    "west new brighton": STATEN_ISLAND,
    "westerleigh": STATEN_ISLAND,
    "willowbrook": STATEN_ISLAND,
    "woodrow": STATEN_ISLAND,
}
