#!/bin/bash

set -ex
set -o pipefail

exec > >(tee /var/log/user_data.log | logger -t user_data) 2>&1
echo BEGIN
BEGINTIME=$(date +%s)
date "+%Y-%m-%d %H:%M:%S"

yum update -y
amazon-linux-extras install -y epel
yum-config-manager --enable epel*
yum install -y git python3 gcc postgresql-devel python3-devel.x86_64 gtk3 dbus-python-devel.x86_64 libXt.x86_64

pip3 install bs4 torrequest awscli boto3 selenium

adduser harvester
HARVESTER_HOME=/home/harvester

mkdir "$HARVESTER_HOME"/.browsing

wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/76.0.1/linux-x86_64/en-US/firefox-76.0.1.tar.bz2
tar xvf firefox-76.0.1.tar.bz2
mv firefox/ opt/
ln -s /opt/firefox/firefox /usr/bin/firefox

wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
tar xzvf geckodriver-v0.26.0-linux64.tar.gz
mv geckodriver "$HARVESTER_HOME"/.browsing/

mkdir "$HARVESTER_HOME"/.aws
cat << EOT > "$HARVESTER_HOME"/.aws/config
[default]
region = us-east-1
output = json
EOT

git clone https://github.com/jschnab/real-estate-scraping.git "$HARVESTER_HOME"/real-estate-scraping
aws s3 cp --recursive s3://real-estate-browsing/config "$HARVESTER_HOME"/.browsing

chown -R harvester:harvester "$HARVESTER_HOME"

cat << EOF > /etc/systemd/system/harvest_re.service
[Unit]
Description=Automated web browser for real estate
After=network.target

[Service]
Type=simple
User=harvester
Group=harvester
ExecStart=/usr/bin/python3 $HARVESTER_HOME/real-estate-scraping/cityrealty/harvest.py
Restart=always
TimeoutStartSec=10
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
EOF

systemctl enable harvest_re.service
systemctl start harvest_re.service

date "+%Y-%m-%d %H:%M:%S"
ENDTIME=$(date +%s)
echo "deployment took $((ENDTIME - BEGINTIME)) seconds"
echo END
